from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from datetime import datetime
import os


def generate_incident_report(incident):
    file_name = f"incident_report_{incident['id']}.pdf"
    file_path = os.path.join("reports", file_name)

    os.makedirs("reports", exist_ok=True)

    c = canvas.Canvas(file_path, pagesize=A4)
    width, height = A4

    y = height - 50

    def draw(text):
        nonlocal y
        c.drawString(50, y, text)
        y -= 18

    draw("INCIDENT RESPONSE REPORT")
    draw("=" * 50)
    draw(f"Incident ID: {incident['id']}")
    draw(f"Created At: {incident.get('created_at')}")
    draw(f"Severity: {incident.get('severity')}")
    draw(f"Status: {incident.get('status')}")
    draw("")

    draw("INVESTIGATION TIMELINE:")
    draw("-" * 30)

    for msg in incident.get("messages", []):
        # truncate content to keep lines tidy
        content = msg.get('content', '')
        draw(f"{msg.get('role', '').upper()}: {content[:90]}")

    draw("")
    draw("Generated by Incident Response Intelligence Agent")
    draw(f"Timestamp: {datetime.utcnow()}")

    c.save()
    return file_path
